#!/usr/bin/env sh

# Setup utility
# by David Oniani <onianidavid@gmail.com>
# MIT License

config() {
    cp -R .config "$HOME"
    cp -R .local "$HOME"

    mkdir -p "$HOME/dl" "$HOME/doc" "$HOME/git" "$HOME/pic" "$HOME/vid" "$HOME/wip"
    mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/msmtp"
    mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"

    sudo touch "/etc/zsh/zshenv"
    printf "export ZDOTDIR=%s/.config/zsh\n" "$HOME" | sudo tee "/etc/zsh/zshenv"

    dir="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugin"
    [ ! -d "$dir/zsh-autosuggestions" ] &&
        git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git \
        "$dir/zsh-autosuggestions"
    [ ! -d "$dir/fast-syntax-highlighting" ] &&
        git clone --depth=1 https://github.com/zdharma-continuum/fast-syntax-highlighting.git \
        "$dir/fast-syntax-highlighting"
}

program() {
    sed 1d programs.csv | while IFS=, read -r tag name description; do
        printf "Installing %s (%s)\n" "$name" "$description"
        case $tag in
            PACMAN) sudo pacman -S  --noconfirm "$name";;
            AUR) paru -S --noconfirm "$name";;
            *) printf "%s\n" "Wrong tag!" >&2 && exit 1;;
        esac
    done
}

nosudo() {
    sudo touch "/etc/sudoers.d/$USER"
    printf "%s ALL=(ALL:ALL) NOPASSWD: ALL\n" "$USER" | sudo tee "/etc/sudoers.d/$USER"

    sudo touch /etc/sudoers.d/disable_admin_file_in_home
    printf "Defaults !admin_flag\n" | sudo tee /etc/sudoers.d/disable_admin_file_in_home
}

help() {
    printf "usage: ./setup [option]\n\
    --config     Copy configuration files\n\
    --nosudo     Configure sudo behavior\n\
    --program    Install all necessary programs\n"
}

case $1 in
    "--config") config;;
    "--nosudo") nosudo;;
    "--program") program;;
    *) help;;
esac
