#!/usr/bin/env sh
while read -r file
do
    case "$1" in
        "f") convert -flop "$file" "$file";;
        "r") convert -rotate 90 "$file" "$file";;
        "R") convert -rotate -90 "$file" "$file";;
        "s") xwallpaper --zoom "$file";;
    esac
done
