#!/usr/bin/env sh

# nsxiv configuration file
# by David Oniani <onianidavid@gmail.com>
# MIT License

while read -r file
do
    case $1 in
        "f") convert -flop "$file" "$file";;
        "r") convert -rotate 90 "$file" "$file";;
        "R") convert -rotate -90 "$file" "$file";;
        "s") nitrogen --set-zoom-fill "$file";;
    esac
done
