#!/usr/bin/env sh

# Lazy git push
# by David Oniani <onianidavid@gmail.com>
# License: GNU GPLv3

git add .
if [ "$1" = "" ]; then
  git commit -m "Update repository"
else
  git commit -m "$1"
fi
git push
