#!/usr/bin/env sh

# File bulk-renaming tool
# by David Oniani <onianidavid@gmail.com>
# License: GNU GPLv3

DIR=$1
BASE=$2

count=0
for filepath in $(find "$DIR" -maxdepth 1 | tail -n +2 | sort); do
  extension=${filepath##*.}
  directory="$(dirname "$filepath")"
  mv "$filepath" "$directory/$BASE$count.$extension"
  count=$((count + 1))
done
