#!/usr/bin/env sh

# Change the wallpaper and generate the colorscheme
# by David Oniani <onianidavid@gmail.com>
# License: GNU GPLv3

# Change a wallpaper and generate a colorscheme
# NOTE: `wallpaper` command works only on macOS
wallpaper set "$1" && wal -n -i "$1"
