[mgr]
prepend_keymap = [
    # Built-in mappings
    { on = "<C-l>", run = "escape --all", desc = "Cancel find, exit visual mode, clear selected, cancel filter, and cancel search." },
    { on = "F", run  = "search_do --via=fd", desc = "Switch to the flat view" },
    { on = "e", run = "open", desc = "Open a file or a directory" },
    { on = "n", run = "create", desc = "Create a new file" },
    { on = [ "g", "D" ], run = "cd ~/Downloads", desc = "Change directory to ~/Downloads" },
    { on = [ "g", "G" ], run = "cd ~/git", desc = "Change directory to ~/git" },
    { on = [ "g", "d" ], run = "cd ~/Documents", desc = "Change directory to ~/Documents" },
    { on = [ "g", "o" ], run = "cd ~/git/dot", desc = "Change directory to ~/git/dot" },
    { on = [ "g", "w" ], run = "cd ~/workspace", desc = "Change directory to ~/workspace" },

    # Plugin mappings
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
]
