[mgr]
prepend_keymap = [
    # Built-in mappings
    { on = "e", run = "open", desc = "Open a file or a directory" },
    { on = "n", run = "create", desc = "Create a new file" },
    { on = [ "g", "d" ], run = "cd ~/Documents", desc = "Change directory to ~/Documents" },
    { on = [ "g", "D" ], run = "cd ~/Downloads", desc = "Change directory to ~/Downloads" },
    { on = [ "g", "G" ], run = "cd ~/Downloads", desc = "Change directory to ~/git" },
    { on = [ "g", "w" ], run = "cd ~/workspace", desc = "Change directory to ~/workspace" },

    # Plugin mappings
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
]
