[mgr]
prepend_keymap = [
    # Navigation
    { on = [ "g", "/" ], run = "cd /", desc = "Go to /" },
    { on = [ "g", "D" ], run = "cd ~/Downloads", desc = "Go to ~/Downloads" },
    { on = [ "g", "G" ], run = "cd ~/git", desc = "Change directory to ~/git" },
    { on = [ "g", "d" ], run = "cd ~/Documents", desc = "Go to ~/Documents" },
    { on = [ "g", "o" ], run = "cd ~/git/dot", desc = "Go to ~/git/dot" },
    { on = [ "g", "t" ], run = "cd ~/git/tex", desc = "Go to ~/git/tex" },
    { on = [ "g", "w" ], run = "cd ~/workspace", desc = "Go to ~/workspace" },
    { on = [ "g", "~" ], run = "cd ~/", desc = "Go to ~/" },

    # Built-in mappings
    { on = "<C-l>", run = "escape --all", desc = "Cancel find/filter/search, exit visual mode, and clear selected." },
    { on = "F", run  = "search_do --via=fd", desc = "Switch to the flat view" },
    { on = "e", run = "open", desc = "Open a file or a directory" },

    # Plugin mappings
    { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
    { on = "<Enter>", run = "plugin smart-enter", desc = "Restore last deleted files/folders" },
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" }
]
