[mgr]
ratio = [2, 3, 4]
show_hidden = true

[preview]
wrap = "yes"
max_width = 1024
max_height = 1024

[plugin]
prepend_fetchers = [
    { id = "git", name = "*", run = "git" },
    { id = "git", name = "*/", run = "git" }
]
