[mgr]
ratio = [2, 3, 4]
show_hidden = true

[preview]
max_height = 4096
max_width = 4096
wrap = "yes"

[tasks]
image_bound = [ 65_535, 65_535 ]

[plugin]
prepend_fetchers = [
    { id = "git", name = "*", run = "git" },
    { id = "git", name = "*/", run = "git" }
]
