# Author: David Oniani <onianidavid@gmail.com>
# Description: mise configuration file
# License: MIT

[tools]
go = "1.26.1"
lua = "5.4.8"
node = "25.8.2"
python = "3.13.11"
rust = "1.94.1"
uv = "0.11.2"

[settings]
node = { gpg_verify = false }
python = { default_packages_file = "~/.config/mise/requirements.txt" }
